import type {
  Appointment,
  AuditLog,
  Barber,
  Block,
  Client,
  GalleryPhoto,
  Invoice,
  Plan,
  Product,
  Service,
  Tenant,
} from "./types"

export const currentTenant: Tenant = {
  id: "tenant_1",
  name: "Barbearia do Tião",
  slug: "barbearia-do-tiao",
  logo_url: "/barbershop-logo.jpg",
  cover_url: "/barbershop-interior.png",
  phone: "(11) 99999-1234",
  address: "Rua Augusta, 1500 — Consolação, São Paulo, SP",
  instagram: "@barbeariadotiao",
  description: "A melhor barbearia clássica do centro de São Paulo desde 1985.",
  plan: "pro",
  status: "active",
  trial_ends_at: "2026-05-12T00:00:00Z",
  created_at: "2024-08-15T10:00:00Z",
  mrr: 99,
}

export const currentUser = {
  id: "user_1",
  name: "Sebastião Oliveira",
  email: "tiao@barbearia.com",
  avatar_url: "/middle-aged-barber.jpg",
  role: "owner" as const,
}

export const services: Service[] = [
  {
    id: "svc_1",
    tenant_id: "tenant_1",
    name: "Corte Masculino Clássico",
    description: "Corte tradicional com tesoura e máquina, finalização com pomada.",
    category: "cabelo",
    duration_min: 30,
    price: 45,
    photo_url: "/classic-haircut.jpg",
    active: true,
    add_ons: [{ id: "add_1", name: "Lavagem", price: 10 }],
    barber_ids: ["barber_1", "barber_2", "barber_3"],
  },
  {
    id: "svc_2",
    tenant_id: "tenant_1",
    name: "Barba Completa",
    description: "Toalha quente, navalha e hidratação.",
    category: "barba",
    duration_min: 30,
    price: 40,
    photo_url: "/beard-trim.png",
    active: true,
    add_ons: [],
    barber_ids: ["barber_1", "barber_2"],
  },
  {
    id: "svc_3",
    tenant_id: "tenant_1",
    name: "Combo Corte + Barba",
    description: "O combo mais pedido. Cabelo e barba impecáveis.",
    category: "combo",
    duration_min: 60,
    price: 75,
    photo_url: "/haircut-and-beard.jpg",
    active: true,
    add_ons: [{ id: "add_2", name: "Sobrancelha", price: 15 }],
    barber_ids: ["barber_1", "barber_2", "barber_3", "barber_4"],
  },
  {
    id: "svc_4",
    tenant_id: "tenant_1",
    name: "Hidratação Capilar",
    description: "Tratamento profundo com produtos premium.",
    category: "tratamento",
    duration_min: 45,
    price: 60,
    photo_url: "/hair-treatment.jpg",
    active: true,
    add_ons: [],
    barber_ids: ["barber_3", "barber_4"],
  },
  {
    id: "svc_5",
    tenant_id: "tenant_1",
    name: "Pigmentação de Barba",
    description: "Realce de cor e cobertura de fios brancos.",
    category: "barba",
    duration_min: 40,
    price: 55,
    photo_url: "/beard-coloring.jpg",
    active: true,
    add_ons: [],
    barber_ids: ["barber_2"],
  },
  {
    id: "svc_6",
    tenant_id: "tenant_1",
    name: "Corte Infantil",
    description: "Corte rápido e divertido para crianças até 10 anos.",
    category: "cabelo",
    duration_min: 25,
    price: 35,
    photo_url: "/kids-haircut.jpg",
    active: true,
    add_ons: [],
    barber_ids: ["barber_1", "barber_3"],
  },
  {
    id: "svc_7",
    tenant_id: "tenant_1",
    name: "Sobrancelha Masculina",
    description: "Design e limpeza de sobrancelhas.",
    category: "tratamento",
    duration_min: 15,
    price: 20,
    photo_url: "/eyebrow-grooming.jpg",
    active: false,
    add_ons: [],
    barber_ids: ["barber_4"],
  },
]

const defaultSchedule = {
  monday: { open: true, start: "09:00", end: "20:00", lunch_start: "12:00", lunch_end: "13:00" },
  tuesday: { open: true, start: "09:00", end: "20:00", lunch_start: "12:00", lunch_end: "13:00" },
  wednesday: { open: true, start: "09:00", end: "20:00", lunch_start: "12:00", lunch_end: "13:00" },
  thursday: { open: true, start: "09:00", end: "20:00", lunch_start: "12:00", lunch_end: "13:00" },
  friday: { open: true, start: "09:00", end: "21:00", lunch_start: "12:00", lunch_end: "13:00" },
  saturday: { open: true, start: "09:00", end: "18:00" },
  sunday: { open: false, start: "09:00", end: "18:00" },
}

export const barbers: Barber[] = [
  {
    id: "barber_1",
    tenant_id: "tenant_1",
    name: "Carlos Mendes",
    bio: "Especialista em cortes clássicos. 15 anos de profissão.",
    email: "carlos@barbearia.com",
    phone: "(11) 98888-1111",
    avatar_url: "/barber-portrait.jpg",
    color: "#2563EB",
    commission_pct: 50,
    active: true,
    schedule: defaultSchedule,
    service_ids: ["svc_1", "svc_2", "svc_3", "svc_6"],
  },
  {
    id: "barber_2",
    tenant_id: "tenant_1",
    name: "Rafael Souza",
    bio: "Mestre na navalha e degradês modernos.",
    email: "rafael@barbearia.com",
    phone: "(11) 98888-2222",
    avatar_url: "/young-barber.jpg",
    color: "#10B981",
    commission_pct: 45,
    active: true,
    schedule: defaultSchedule,
    service_ids: ["svc_1", "svc_2", "svc_3", "svc_5"],
  },
  {
    id: "barber_3",
    tenant_id: "tenant_1",
    name: "André Lima",
    bio: "Foco em tratamentos e hidratações.",
    email: "andre@barbearia.com",
    phone: "(11) 98888-3333",
    avatar_url: "/bearded-barber.jpg",
    color: "#F59E0B",
    commission_pct: 50,
    active: true,
    schedule: defaultSchedule,
    service_ids: ["svc_1", "svc_3", "svc_4", "svc_6"],
  },
  {
    id: "barber_4",
    tenant_id: "tenant_1",
    name: "Lucas Pereira",
    bio: "Recém formado, especialista em cortes infantis.",
    email: "lucas@barbearia.com",
    phone: "(11) 98888-4444",
    avatar_url: "/junior-barber.jpg",
    color: "#EF4444",
    commission_pct: 40,
    active: true,
    schedule: defaultSchedule,
    service_ids: ["svc_3", "svc_4", "svc_7"],
  },
]

export const clients: Client[] = [
  {
    id: "cli_1",
    tenant_id: "tenant_1",
    name: "João Silva",
    phone: "(11) 91111-1111",
    email: "joao@email.com",
    birthday: "1990-04-30",
    avatar_url: "/diverse-businessman.png",
    tags: ["vip", "aniversariante"],
    total_spent: 2400,
    visit_count: 32,
    last_visit_at: "2026-04-22T15:00:00Z",
    notes: "Sempre pede o corte degradê. Alérgico a pomada com álcool.",
    preferences: ["Degradê médio", "Sem álcool", "Café preto sem açúcar"],
    created_at: "2023-06-10T10:00:00Z",
  },
  {
    id: "cli_2",
    tenant_id: "tenant_1",
    name: "Pedro Almeida",
    phone: "(11) 92222-2222",
    email: "pedro@email.com",
    birthday: "1985-11-12",
    avatar_url: "/professional-man.png",
    tags: ["vip"],
    total_spent: 1850,
    visit_count: 24,
    last_visit_at: "2026-04-15T10:30:00Z",
    notes: "Cliente desde a inauguração. Sempre marca quinzenalmente.",
    preferences: ["Corte clássico", "Conversa de futebol"],
    created_at: "2023-01-20T10:00:00Z",
  },
  {
    id: "cli_3",
    tenant_id: "tenant_1",
    name: "Mateus Rocha",
    phone: "(11) 93333-3333",
    email: "mateus@email.com",
    birthday: "1995-07-22",
    avatar_url: "/young-professional-man.png",
    tags: ["novo"],
    total_spent: 120,
    visit_count: 2,
    last_visit_at: "2026-04-20T14:00:00Z",
    notes: "Indicado pelo João Silva.",
    preferences: [],
    created_at: "2026-03-15T10:00:00Z",
  },
  {
    id: "cli_4",
    tenant_id: "tenant_1",
    name: "Felipe Costa",
    phone: "(11) 94444-4444",
    email: "felipe@email.com",
    birthday: "1988-02-05",
    avatar_url: "/man-glasses.png",
    tags: [],
    total_spent: 680,
    visit_count: 9,
    last_visit_at: "2026-03-28T16:00:00Z",
    notes: "",
    preferences: ["Barba bem feita"],
    created_at: "2024-11-12T10:00:00Z",
  },
  {
    id: "cli_5",
    tenant_id: "tenant_1",
    name: "Bruno Martins",
    phone: "(11) 95555-5555",
    email: "bruno@email.com",
    birthday: "1992-09-18",
    avatar_url: "/man-beard.png",
    tags: ["inativo"],
    total_spent: 320,
    visit_count: 4,
    last_visit_at: "2025-11-10T11:00:00Z",
    notes: "Não vem desde novembro do ano passado.",
    preferences: [],
    created_at: "2024-05-08T10:00:00Z",
  },
  {
    id: "cli_6",
    tenant_id: "tenant_1",
    name: "Ricardo Santos",
    phone: "(11) 96666-6666",
    email: "ricardo@email.com",
    birthday: "1980-12-25",
    avatar_url: "/older-man-portrait.png",
    tags: ["vip"],
    total_spent: 3200,
    visit_count: 45,
    last_visit_at: "2026-04-25T09:00:00Z",
    notes: "Cliente fiel. Filho do Sr. Antônio.",
    preferences: ["Sempre com Carlos"],
    created_at: "2022-08-01T10:00:00Z",
  },
  {
    id: "cli_7",
    tenant_id: "tenant_1",
    name: "Diego Ferreira",
    phone: "(11) 97777-7777",
    email: "diego@email.com",
    birthday: "1998-06-15",
    avatar_url: "/young-man.jpg",
    tags: ["novo"],
    total_spent: 75,
    visit_count: 1,
    last_visit_at: "2026-04-26T11:30:00Z",
    notes: "Primeira visita, gostou muito.",
    preferences: [],
    created_at: "2026-04-26T10:00:00Z",
  },
  {
    id: "cli_8",
    tenant_id: "tenant_1",
    name: "Henrique Dias",
    phone: "(11) 98888-9999",
    email: "henrique@email.com",
    birthday: "1993-04-29",
    avatar_url: "/man-hat.jpg",
    tags: ["aniversariante"],
    total_spent: 540,
    visit_count: 8,
    last_visit_at: "2026-04-10T17:00:00Z",
    notes: "Aniversário hoje! Mandar mensagem.",
    preferences: ["Corte social"],
    created_at: "2025-02-20T10:00:00Z",
  },
]

const today = new Date()
today.setHours(0, 0, 0, 0)

function makeDate(daysOffset: number, hour: number, minute = 0): string {
  const d = new Date(today)
  d.setDate(d.getDate() + daysOffset)
  d.setHours(hour, minute, 0, 0)
  return d.toISOString()
}

export const appointments: Appointment[] = [
  {
    id: "apt_1",
    tenant_id: "tenant_1",
    client_id: "cli_1",
    barber_id: "barber_1",
    service_id: "svc_3",
    start_at: makeDate(0, 9, 0),
    end_at: makeDate(0, 10, 0),
    status: "confirmed",
    price: 75,
    notes: "Cliente pediu pra deixar bem curto atrás",
  },
  {
    id: "apt_2",
    tenant_id: "tenant_1",
    client_id: "cli_2",
    barber_id: "barber_2",
    service_id: "svc_1",
    start_at: makeDate(0, 10, 0),
    end_at: makeDate(0, 10, 30),
    status: "in_progress",
    price: 45,
    notes: "",
  },
  {
    id: "apt_3",
    tenant_id: "tenant_1",
    client_id: "cli_3",
    barber_id: "barber_3",
    service_id: "svc_4",
    start_at: makeDate(0, 11, 0),
    end_at: makeDate(0, 11, 45),
    status: "confirmed",
    price: 60,
    notes: "",
  },
  {
    id: "apt_4",
    tenant_id: "tenant_1",
    client_id: "cli_4",
    barber_id: "barber_1",
    service_id: "svc_2",
    start_at: makeDate(0, 14, 0),
    end_at: makeDate(0, 14, 30),
    status: "pending",
    price: 40,
    notes: "",
  },
  {
    id: "apt_5",
    tenant_id: "tenant_1",
    client_id: "cli_6",
    barber_id: "barber_1",
    service_id: "svc_3",
    start_at: makeDate(0, 15, 0),
    end_at: makeDate(0, 16, 0),
    status: "confirmed",
    price: 75,
    notes: "",
  },
  {
    id: "apt_6",
    tenant_id: "tenant_1",
    client_id: "cli_7",
    barber_id: "barber_4",
    service_id: "svc_3",
    start_at: makeDate(0, 16, 30),
    end_at: makeDate(0, 17, 30),
    status: "confirmed",
    price: 75,
    notes: "Primeira visita",
  },
  {
    id: "apt_7",
    tenant_id: "tenant_1",
    client_id: "cli_8",
    barber_id: "barber_2",
    service_id: "svc_1",
    start_at: makeDate(0, 17, 0),
    end_at: makeDate(0, 17, 30),
    status: "pending",
    price: 45,
    notes: "",
  },
  {
    id: "apt_8",
    tenant_id: "tenant_1",
    client_id: "cli_5",
    barber_id: "barber_3",
    service_id: "svc_3",
    start_at: makeDate(0, 18, 0),
    end_at: makeDate(0, 19, 0),
    status: "confirmed",
    price: 75,
    notes: "",
  },
  // Yesterday completed
  {
    id: "apt_9",
    tenant_id: "tenant_1",
    client_id: "cli_1",
    barber_id: "barber_1",
    service_id: "svc_1",
    start_at: makeDate(-1, 10, 0),
    end_at: makeDate(-1, 10, 30),
    status: "completed",
    price: 45,
    notes: "",
    payment_method: "pix",
  },
  {
    id: "apt_10",
    tenant_id: "tenant_1",
    client_id: "cli_2",
    barber_id: "barber_2",
    service_id: "svc_3",
    start_at: makeDate(-1, 14, 0),
    end_at: makeDate(-1, 15, 0),
    status: "completed",
    price: 75,
    notes: "",
    payment_method: "credito",
  },
  // Tomorrow
  {
    id: "apt_11",
    tenant_id: "tenant_1",
    client_id: "cli_3",
    barber_id: "barber_1",
    service_id: "svc_3",
    start_at: makeDate(1, 9, 0),
    end_at: makeDate(1, 10, 0),
    status: "confirmed",
    price: 75,
    notes: "",
  },
  {
    id: "apt_12",
    tenant_id: "tenant_1",
    client_id: "cli_4",
    barber_id: "barber_2",
    service_id: "svc_2",
    start_at: makeDate(1, 11, 0),
    end_at: makeDate(1, 11, 30),
    status: "confirmed",
    price: 40,
    notes: "",
  },
]

export const blocks: Block[] = [
  {
    id: "blk_1",
    tenant_id: "tenant_1",
    start_at: makeDate(3, 0),
    end_at: makeDate(3, 23, 59),
    reason: "Feriado nacional",
    barber_ids: [],
    full_day: true,
  },
  {
    id: "blk_2",
    tenant_id: "tenant_1",
    start_at: makeDate(2, 12),
    end_at: makeDate(2, 14),
    reason: "Reunião de equipe",
    barber_ids: ["barber_1", "barber_2"],
    full_day: false,
  },
]

export const galleryPhotos: GalleryPhoto[] = [
  { id: "ph_1", tenant_id: "tenant_1", url: "/modern-haircut.jpg", caption: "Degradê moderno", show_in_booking: true, uploaded_at: "2026-04-20T10:00:00Z" },
  { id: "ph_2", tenant_id: "tenant_1", url: "/classic-haircut.jpg", caption: "Corte clássico", show_in_booking: true, uploaded_at: "2026-04-19T10:00:00Z" },
  { id: "ph_3", tenant_id: "tenant_1", url: "/beard-trim.png", caption: "Barba alinhada", show_in_booking: true, uploaded_at: "2026-04-18T10:00:00Z" },
  { id: "ph_4", tenant_id: "tenant_1", url: "/haircut-and-beard.jpg", caption: "Combo completo", show_in_booking: true, uploaded_at: "2026-04-17T10:00:00Z" },
  { id: "ph_5", tenant_id: "tenant_1", url: "/barbershop-interior.png", caption: "Nosso espaço", show_in_booking: true, uploaded_at: "2026-04-16T10:00:00Z" },
  { id: "ph_6", tenant_id: "tenant_1", url: "/hair-treatment.jpg", caption: "Hidratação", show_in_booking: false, uploaded_at: "2026-04-15T10:00:00Z" },
  { id: "ph_7", tenant_id: "tenant_1", url: "/kids-haircut.jpg", caption: "Corte infantil", show_in_booking: true, uploaded_at: "2026-04-14T10:00:00Z" },
  { id: "ph_8", tenant_id: "tenant_1", url: "/beard-coloring.jpg", caption: "Pigmentação de barba", show_in_booking: true, uploaded_at: "2026-04-13T10:00:00Z" },
]

export const products: Product[] = [
  { id: "prod_1", tenant_id: "tenant_1", name: "Pomada Modeladora", price: 45, stock: 24, photo_url: "/hair-pomade.jpg" },
  { id: "prod_2", tenant_id: "tenant_1", name: "Óleo para Barba", price: 38, stock: 12, photo_url: "/beard-oil.jpg" },
  { id: "prod_3", tenant_id: "tenant_1", name: "Shampoo Premium", price: 55, stock: 18, photo_url: "/shampoo-bottle.jpg" },
  { id: "prod_4", tenant_id: "tenant_1", name: "Pente de Madeira", price: 25, stock: 30, photo_url: "/wooden-comb.jpg" },
]

export const invoices: Invoice[] = [
  { id: "inv_1", tenant_id: "tenant_1", amount: 99, date: "2026-04-01", status: "paid", pdf_url: "#" },
  { id: "inv_2", tenant_id: "tenant_1", amount: 99, date: "2026-03-01", status: "paid", pdf_url: "#" },
  { id: "inv_3", tenant_id: "tenant_1", amount: 99, date: "2026-02-01", status: "paid", pdf_url: "#" },
  { id: "inv_4", tenant_id: "tenant_1", amount: 49, date: "2026-01-01", status: "paid", pdf_url: "#" },
]

export const plans: Plan[] = [
  {
    id: "starter",
    name: "Starter",
    price: 49,
    max_barbers: 2,
    max_appointments: 200,
    features: [
      "Até 2 barbeiros",
      "Até 200 agendamentos/mês",
      "Agenda online",
      "Cadastro de clientes",
      "Relatórios básicos",
    ],
  },
  {
    id: "pro",
    name: "Pro",
    price: 99,
    max_barbers: 6,
    max_appointments: 1000,
    features: [
      "Até 6 barbeiros",
      "Até 1.000 agendamentos/mês",
      "Página pública de agendamento",
      "PDV integrado",
      "Relatórios avançados",
      "Comissões automáticas",
      "Galeria de fotos",
    ],
  },
  {
    id: "premium",
    name: "Premium",
    price: 199,
    max_barbers: 999,
    max_appointments: 99999,
    features: [
      "Barbeiros ilimitados",
      "Agendamentos ilimitados",
      "Multi-unidades",
      "API dedicada",
      "Integração WhatsApp Business",
      "Suporte prioritário 24/7",
      "Gerente de sucesso",
    ],
  },
]

// Super admin global mock data
export const allTenants: Tenant[] = [
  currentTenant,
  {
    id: "tenant_2",
    name: "Barbearia Vintage",
    slug: "vintage",
    logo_url: "/vintage-logo.jpg",
    cover_url: "/vintage-shop.jpg",
    phone: "(21) 98888-7777",
    address: "Av. Atlântica, 200 — Rio de Janeiro, RJ",
    instagram: "@vintagebarber",
    description: "Barbearia retrô no coração de Copacabana.",
    plan: "premium",
    status: "active",
    trial_ends_at: "2025-09-15T00:00:00Z",
    created_at: "2024-09-01T10:00:00Z",
    mrr: 199,
  },
  {
    id: "tenant_3",
    name: "Modern Cuts",
    slug: "modern-cuts",
    logo_url: "/modern-logo.png",
    cover_url: "/modern-shop.jpg",
    phone: "(31) 97777-8888",
    address: "Rua da Bahia, 1000 — Belo Horizonte, MG",
    instagram: "@moderncuts",
    description: "Cortes modernos para a nova geração.",
    plan: "starter",
    status: "trial",
    trial_ends_at: "2026-05-08T00:00:00Z",
    created_at: "2026-04-08T10:00:00Z",
    mrr: 0,
  },
  {
    id: "tenant_4",
    name: "Premium Barber",
    slug: "premium-barber",
    logo_url: "/premium-logo.jpg",
    cover_url: "/premium-shop.jpg",
    phone: "(41) 96666-5555",
    address: "Rua XV de Novembro, 500 — Curitiba, PR",
    instagram: "@premiumbarber",
    description: "Experiência premium em cada visita.",
    plan: "pro",
    status: "active",
    trial_ends_at: "2025-08-01T00:00:00Z",
    created_at: "2024-08-01T10:00:00Z",
    mrr: 99,
  },
  {
    id: "tenant_5",
    name: "Old School Barber",
    slug: "old-school",
    logo_url: "/oldschool-logo.jpg",
    cover_url: "/oldschool-shop.jpg",
    phone: "(51) 95555-4444",
    address: "Rua dos Andradas, 800 — Porto Alegre, RS",
    instagram: "@oldschoolbarber",
    description: "Tradição desde 1970.",
    plan: "starter",
    status: "suspended",
    trial_ends_at: "2025-12-01T00:00:00Z",
    created_at: "2024-11-15T10:00:00Z",
    mrr: 0,
  },
  {
    id: "tenant_6",
    name: "Top Cut Barber",
    slug: "top-cut",
    logo_url: "/topcut-logo.jpg",
    cover_url: "/topcut-shop.jpg",
    phone: "(85) 94444-3333",
    address: "Av. Beira Mar, 1000 — Fortaleza, CE",
    instagram: "@topcutbarber",
    description: "Cortes top de linha à beira-mar.",
    plan: "pro",
    status: "churned",
    trial_ends_at: "2025-06-01T00:00:00Z",
    created_at: "2024-06-01T10:00:00Z",
    mrr: 0,
  },
]

export const auditLogs: AuditLog[] = [
  { id: "log_1", tenant_id: "tenant_1", tenant_name: "Barbearia do Tião", user_name: "Sebastião Oliveira", action: "service.created", entity: "Pigmentação de Barba", created_at: "2026-04-29T14:23:00Z", ip: "201.45.123.10" },
  { id: "log_2", tenant_id: "tenant_2", tenant_name: "Barbearia Vintage", user_name: "Marcos Silva", action: "appointment.cancelled", entity: "apt_889", created_at: "2026-04-29T13:50:00Z", ip: "189.20.45.78" },
  { id: "log_3", tenant_id: "tenant_3", tenant_name: "Modern Cuts", user_name: "Lucas Andrade", action: "tenant.created", entity: "Modern Cuts", created_at: "2026-04-29T11:12:00Z", ip: "177.18.99.41" },
  { id: "log_4", tenant_id: "tenant_4", tenant_name: "Premium Barber", user_name: "Roberto Pinto", action: "barber.invited", entity: "felipe@premium.com", created_at: "2026-04-29T10:05:00Z", ip: "200.10.15.92" },
  { id: "log_5", tenant_id: "tenant_5", tenant_name: "Old School Barber", user_name: "admin@aft.com", action: "tenant.suspended", entity: "Old School Barber", created_at: "2026-04-28T18:30:00Z", ip: "10.0.0.1" },
  { id: "log_6", tenant_id: "tenant_1", tenant_name: "Barbearia do Tião", user_name: "Sebastião Oliveira", action: "client.updated", entity: "João Silva", created_at: "2026-04-28T16:15:00Z", ip: "201.45.123.10" },
  { id: "log_7", tenant_id: "tenant_2", tenant_name: "Barbearia Vintage", user_name: "Marcos Silva", action: "plan.upgraded", entity: "pro → premium", created_at: "2026-04-28T14:00:00Z", ip: "189.20.45.78" },
  { id: "log_8", tenant_id: "tenant_6", tenant_name: "Top Cut Barber", user_name: "admin@aft.com", action: "tenant.churned", entity: "Top Cut Barber", created_at: "2026-04-27T09:00:00Z", ip: "10.0.0.1" },
]

// Helpers
export function getClient(id: string): Client | undefined {
  return clients.find((c) => c.id === id)
}
export function getBarber(id: string): Barber | undefined {
  return barbers.find((b) => b.id === id)
}
export function getService(id: string): Service | undefined {
  return services.find((s) => s.id === id)
}

export const weekdayLabels: Record<string, string> = {
  monday: "Segunda",
  tuesday: "Terça",
  wednesday: "Quarta",
  thursday: "Quinta",
  friday: "Sexta",
  saturday: "Sábado",
  sunday: "Domingo",
}
